# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailgunconf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MG(object):
    def setupUi(self, MG):
        MG.setObjectName("MG")
        MG.resize(794, 452)
        self.groupBox = QtWidgets.QGroupBox(MG)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 741, 391))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 80, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 151, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(180, 80, 491, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 130, 491, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 230, 151, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 180, 491, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 230, 491, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(310, 310, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 320, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(150, 330, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(MG)
        QtCore.QMetaObject.connectSlotsByName(MG)

    def retranslateUi(self, MG):
        _translate = QtCore.QCoreApplication.translate
        MG.setWindowTitle(_translate("MG", "Configuration"))
        self.groupBox.setTitle(_translate("MG", "Mail Gun Configuration"))
        self.label.setText(_translate("MG", "Mail Gun Domain"))
        self.label_2.setText(_translate("MG", "Mail Gun API Key"))
        self.label_3.setText(_translate("MG", "Sender Name"))
        self.label_4.setText(_translate("MG", "Sender Email"))
        self.pushButton.setText(_translate("MG", "Save"))
        self.pushButton_2.setText(_translate("MG", "Close"))
        self.label_5.setText(_translate("MG", "Saved!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MG = QtWidgets.QDialog()
    ui = Ui_MG()
    ui.setupUi(MG)
    MG.show()
    sys.exit(app.exec_())
